### PR TITLE
Added watermelon image and var

### PR DESCRIPTION
**Pull request by RitwikGupta**

### CODE REVIEW

**Comment by jtmarmon** [comment]
pepes only please

**Comment by RitwikGupta** [comment]
Pls see https://www.facebook.com/groups/423766264446358/permalink/520555464767437/. This is in regards to MellonHeads at CMU.

**Comment by jtmarmon** [comment]
> 2015
> i give a fuck about your stupid facebook group
naw

**Comment by RitwikGupta** [comment]
> Being oppressed by jtmarmon
ok

**Comment by aroman** [comment]
FORKING HAS COMMENCED

screen shot 2015-09-08 at 6 09 54 pm

IO.JS/LIBREOFFICE TAKE NOTE!!!

https://github.com/MellonHeads/pepify
https://github.com/RitwikGupta/melonlordify.js

**Pull request closed without merging**
